### ISSUE TITLE
NaN probabilities

### ISSUE THREAD

**Issue by ghost** [traets/idefix#9]
Hi,

Below my code. I got NaN values for the probabilities. Do you know why?

at.lvls = c(3,3,5,6)
c.type = c("E", "E", "C", "C")
con.lvls = list(c(12,16,20,24,28), c(250, 350, 450, 550, 650, 750))
cs = Profiles(lvls=at.lvls, coding=c.type, c.lvls = con.lvls)

mu=c(0.5, 0.3, 0.4, 0.6, 0.5, 0.4)
sigma = diag(length(mu))
set.seed(123)
M = MASS::mvrnorm(n = 500, mu = mu, Sigma = sigma)
D = Modfed(cand.set = cs, n.sets = 6, n.alts = 2, par.draws = M)

Kind regards, Sabine

**Comment by traets** [comment]
Hi Sabine, 

You probably get NAN values because you specify very large "con.lvls". Computing the utility will cause numerical problems (due to the the exponential). In addition, as the levels of the last attribute are considerably larger than the previous ones, they will dominate the design solution. I would advice to keep all attribute levels at the same scale and fairly small (for example by using scale() in R).  

Kind regards, 

Frits

**Comment by ghost** [comment]
Hi Frits,

Thank you for the reply. Would another solution be to effects code the continuous variables?

Kind regards,

Sabine

**Comment by traets** [comment]
That would also solve the problem, and will likely result in a more balanced design (compared to using continuous variables). But since you will have more parameters to estimate, you will also need to increase the number of choice sets. 

Frits
